version: '3'
services:
  nats_server:
    container_name: kalyannatsserver
    image: 'nats'
    volumes:
      - .:/keus-app
    command: "-c ./keus-app/nats.config"
    ports:
      - 9697:9697
      - 4362:4362
      - 4369:4369
      - 4376:4376
  
      